---
- name: Install Mattermost with calls
  hosts: local
  tasks:
    - name: Open TCP ports
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
        proto: tcp
      loop:
        - '80'
        - '443'
        - '3443'
        - '8045'
    - name: Open UDP ports
      community.general.ufw:
        rule: allow
        port: '{{ item }}'
        proto: udp
      loop:
        - '8443'
        - '3478'
    - name: Import Mattermost GPG public key
      ansible.builtin.get_url:
        url: https://deb.packages.mattermost.com/pubkey.gpg
        dest: /usr/share/keyrings/mattermost-archive-keyring.gpg
    - name: Ensure debconf is installed
      ansible.builtin.apt:
        name: debconf-utils
        update_cache: yes
    - name: Set Mattermost domain
      ansible.builtin.debconf:
        name: mattermost-omnibus
        question: mattermost-omnibus/domain
        value: "{{ lookup('ansible.builtin.env', 'SERVER_DOMAIN') }}"
        vtype: string
    - name: Set Mattermost email
      ansible.builtin.debconf:
        name: mattermost-omnibus
        question: mattermost-omnibus/email
        value: "{{ lookup('ansible.builtin.env', 'ADMIN_EMAIL') }}"
        vtype: string
    - name: Install mattermost-omnibus
      ansible.builtin.apt:
        name: mattermost-omnibus
      environment:
        DEBIAN_FRONTEND: noninteractive
    - name: Enable calls for everyone
      ansible.builtin.command: mmctl config set "PluginSettings.Plugins.com.mattermost.calls.defaultenabled" "true"
    - name: Set Mattermost server name
      ansible.builtin.command: mmctl config set "ServiceSettings.SiteName" "{{ lookup('ansible.builtin.env', 'SERVER_NAME') }}"
